#!/bin/bash
#pm2 start index.js --node-args="--experimental-json-modules" --watch && pm2 logs
forever start -c "node --experimental-json-modules" -a index.js && forever logs -c "node --experimental-json-modules" index.js -f

